server:
  port: 8081
spring:
  application:
    name: auth-service
  data:
    mongodb:
      database: bidify
      port: 27017
      host: localhost
keycloak:
  realm_id: bidify
  url: http://localhost:8080
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka
