server:
  port: 8082
spring:
  application:
    name: dictionary-service
  data:
    mongodb:
      database: bidify
      port: 27017
      host: localhost
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
mongock:
  change-logs-scan-package: kz.bidify.dictionaryservice.data
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka