server:
  port: 8083
spring:
  application:
    name: product-service
  data:
    mongodb:
      database: bidify
      port: 27017
      host: localhost
    redis:
      host: localhost
      port: 6379
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka